### ISSUE TITLE
auto punishment system

### ISSUE THREAD

**Issue by NoIdentityCommune** [Synapz1/WarningManager#2]
Hello,

i was testing you plugin for usage and i miss something or i do something wrong.

the auto punishment system you can only set a warning for sending a warning what i tried is this:
http://pastebin.com/mCyqcd1p
sorry it is in my language (netherlands)
its you can assign a line of punishment wat he is doing if he is saying bad words you can do like /warn [name] "badword(you can choose yourself)" and then he picks the line with that punsihments.

i hope you will understand me i dont have the best inglish 

greetings,
noidentity

**Comment by Synapz1** [comment]
So you want sections? Like a spam mute and an advertise mute, so it would look:

/warn spam <player>

or 

/warn advertise <player>

etc.. if you add more?

Then each would be a different punishment?

**Comment by NoIdentityCommune** [comment]
yea /warn spam %player% or /warn hack,advertise,scold,grief/steal,spam.
and each a different punishment that you can configure yourself ofcourse

maybe if it is posseble can i get it in my language?
and is there a possebility for mysql?

**Comment by NoIdentityCommune** [comment]
hey,
how is it going atm ??

greetings,
noidentity

**Comment by Synapz1** [comment]
I will be pushing out a commit in a few minutes with the new update! 

Download it from here (it will be v1.8):
https://www.spigotmc.org/resources/warningmanager.11381/
