### ISSUE TITLE
MySQL

### ISSUE THREAD

**Issue by NoIdentityCommune** [Synapz1/WarningManager#3]
Hey Synapz1

realy nice update!.

can i ask you for 1 favor can you make it MySQL

we have more server linked together with MySQL so we realy wanted everything connected.
Can you make that if you can it wil be realy awesome!

And keep up your work realy awesome !

Greetings,
NoIdentity

EDIT: i found a bug with /wreload if you change a punishments name or command or en new punishment and you do /wreload it wont load the new things only the old lines if i do restart the server it wil work.

**Comment by Synapz1** [comment]
Yeah I have been wanting to add MySQL for awhile. I will look into that :)

As for the /wreload bug, I will also look into that. 

Thanks.

If I do not have any updates be sure to remind me again here.

**Comment by NoIdentityCommune** [comment]
Hey Synapz1,

how is it going with the MySQL and that bug ?

greetings,

NoIdentity

**Comment by Synapz1** [comment]
I'll try and get to it by Sunday

**Comment by Synapz1** [comment]
@NoIdentityCommune I am going to get this soon. But I have no way to test it. Can you help test it I can send you the file or something after I finish?

**Comment by NoIdentityCommune** [comment]
hey synapz1
the head host is not online so i cant get it on the database but he wil be on in some hours its 1:48pm here he wil be on around 5pm so i wil ask him but i think it wil be good so you can send it if you want.

greetings,
noidentity

**Comment by Synapz1** [comment]
I will send you a link I have to finish adding it within the next few days

**Comment by NoIdentityCommune** [comment]
i will see it soon :)

**Comment by NoIdentityCommune** [comment]
hey Synapz1,

i got a yes for it. that means we can test it.

greetings,
noidentity

**Comment by Synapz1** [comment]
Ok I have been busy and had no a lot of time to even attempt this.

**Comment by ghost** [comment]
Adding MySQL support. :p @NoIdentityCommune  can you send a link of your warnings.yml file for me? It would help speed things up a bit.

**Comment by NoIdentityCommune** [comment]
i dont know why you need it but its completely stock atm no warnings to players in it ..

**Comment by ghost** [comment]
Oh just because I never actually generated one with warnings haha. No worries I can still do it if i generate the file :p

**Comment by NoIdentityCommune** [comment]
hey how is it going ?

**Comment by Synapz1** [comment]
New updated fixed punishments not reloading on /wreload after they were changed in config.yml

It also added another offline player addition from @Fridgey which send players messages if they were offline from a warning

I want to get SQL out in the next update, version 2.0 :dancer:

**Comment by NoIdentityCommune** [comment]
when wil version 2.0 come out? in a week or

**Comment by ghost** [comment]
I've been a little busy, I'm going to finish the MySQL within a few days if I have time, maybe even today I'll see if I can

**Comment by NoIdentityCommune** [comment]
hey how is it going?

**Comment by NoIdentityCommune** [comment]
hey @Fridgey @Synapz1 ,

how is it going with the MySQL??

Greetings Noidentity,

**Comment by Synapz1** [comment]
Sorry this is taking so long. I believe @Fridgey has been working and I so not know much about SQL. We left off at a tough spot about the layout of how we should do this because players can have an unlimited amount of warnings

**Comment by ghost** [comment]
@NoIdentityCommune @Synapz1 Made some progress, will finish this up soon.

**Comment by NoIdentityCommune** [comment]
@Fridgey @Synapz1 nice to hear :D

**Comment by ghost** [comment]
@NoIdentityCommune @Synapz1 Sorry for the long wait. I have made great progress today and it's nearing completion. You can check the latest push i made here: https://github.com/Fridgey/WarningManager/commit/a43c367eec2135f23de304984b8016e690cd000e

**Comment by Synapz1** [comment]
@NoIdentityCommune thanks! @Fridgey finished with SQL. It will be on Spigot/Bukkit shortly :)
