### ISSUE TITLE
Offline Warning

### ISSUE THREAD

**Issue by NyleGarcia** [Synapz1/WarningManager#4]
When warning someone who is offline it does not notify them when they log in can you please add this feature.

**Comment by Synapz1** [comment]
Will look into adding this

**Comment by ghost** [comment]
Started work on this. Have a good structure down but haven't tested it yet.

**Comment by Synapz1** [comment]
Ooo looks nice

**Comment by ghost** [comment]
Test it for yourself @Synapz1  and close this if  it's ok.

**Comment by Synapz1** [comment]
I will test it later today thanks!
