### ISSUE TITLE
Maybe a good idea.

### ISSUE THREAD

**Issue by NoIdentityCommune** [Synapz1/WarningManager#7]
hey synapz,

i got a good idea maybe a simple 1,

you now can only see a warning from  someone if you know his name, but if you didnt warn him and dont know he was warned you cant see it that fast so what about a command that show you the last warnings that where given by a staffmember to a player.

greetings ,
Stefan

**Comment by Synapz1** [comment]
Warnings say the date so you can use /check and see the last warnings. Plus warnings are stored in order

**Comment by NoIdentityCommune** [comment]
if i do /check i need to fill in a name of a player
i want something that you see just everything of that day. otherwise i need to fill in every1 name to look  what my people are warning people for.

**Comment by ghost** [comment]
I like this idea. @NoIdentityCommune I know it has been a while, but do you still want this?
