### ISSUE TITLE
Source code not updated to 2.2

### ISSUE THREAD

**Issue by au2001** [Synapz1/WarningManager#8]
Hello @Synapz1,

There has been an update to the plugin on the [Spigot page](https://www.spigotmc.org/resources/warningmanager.11381/update?update=182880) on August 21, but there wasn't any commit on this GitHub since June 30.
Could you please commit your latest changes, that include the new `warning-age` setting, so that developers can participate?

The 2.2 update posted on Spigot contains debug messages that should have been removed.
I would have liked to remove them myself to avoid you to spend time in this, but I it can't be done unless you share your latest code on GitHub.

![Unwanted debug messages when using /warn](https://user-images.githubusercontent.com/6292584/31320903-c632a8f6-ac7c-11e7-8c5b-a77e9a480df3.png)

Thanks

**Comment by Synapz1** [comment]
Thanks, I must have forgotten to commit and push. 

Updated to latest now; however, I could not find anything matching that debug message.
